name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install sbcl
          curl -O https://beta.quicklisp.org/quicklisp.lisp
          sbcl --load quicklisp.lisp --eval "(quicklisp-quickstart:install)" --eval "(ql-util:without-prompting (ql:add-to-init-file))" --quit
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_lisp_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.5.1 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: sbcl --non-interactive --load example.lisp
